name: BiBiT-Golang
description: App Description
ignoreFiles: .git
modules:
- name: MOD
  language: go1.x
  description: Module description
  functions:
  - name: handler
    entry: hello.go
    description: the entry point for the function
